# Generated by Django 4.2.2 on 2023-06-20 11:07

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('edicao', models.DateField(auto_now=True, verbose_name='Edição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('etapa', models.CharField(max_length=50, verbose_name='Etapa')),
                ('objetivo', models.CharField(max_length=50, verbose_name='Objetivo')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 400, 'width': 640}}, verbose_name='Imagem')),
                ('descricao', models.TextField(max_length=150, null=True, verbose_name='descricao')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
        migrations.AlterField(
            model_name='membro',
            name='foto',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 400, 'width': 400}}, verbose_name='Foto'),
        ),
    ]
