# Generated by Django 4.2.2 on 2023-06-20 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_registros_delete_registro_alter_membro_foto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registros',
            new_name='Registro',
        ),
    ]
