# Generated by Django 4.2.2 on 2023-06-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_registros_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='data',
            field=models.DateField(help_text='Formato: dd/mm/aa', null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='etapa',
            field=models.CharField(choices=[('desenvolvimento', 'Desvolvimento'), ('pesquisa', 'Pesquisa'), ('aplicacao', 'Aplicação')], max_length=20, verbose_name='Etapa'),
        ),
    ]
