# Generated by Django 4.2.2 on 2023-06-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_registro_data_alter_registro_etapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugestoesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('edicao', models.DateField(auto_now=True, verbose_name='Edição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('mensagem', models.TextField(max_length=500, verbose_name='Sugestões')),
            ],
            options={
                'verbose_name': 'Sugestão',
                'verbose_name_plural': 'Sugestões',
            },
        ),
        migrations.AlterField(
            model_name='registro',
            name='etapa',
            field=models.CharField(choices=[('desenvolvimento', 'Desenvolvimento'), ('pesquisa', 'Pesquisa'), ('aplicacao', 'Aplicação')], max_length=20, verbose_name='Etapa'),
        ),
    ]
